let allmusic = [
    {
        name: " Mahiye Jinna Sona",
        artist: "Darshan Raval",
        img: "c1",
        src: "1",
    },
    {
        name: " Ki Rabba Janda",
        artist: "Arjit Singh",
        img: "c2",
        src: "2",
    },
    {
        name: "Kaseriya",
        artist: "Arjit Singh",
        img: "c3",
        src: "3",
    },
    {
        name: "Kusu Kusu",
        artist: "Zahrah S Khan",
        img: "c4",
        src: "4",
    },
    {
        name: "Bijlee Bijlee",
        artist: "Harrdy Sandhu",
        img: "c5",
        src: "5",
    },
    {
        name: " Let Me Love You",
        artist: "DJ Lijo Remix",
        img: "c6",
        src: "6",
    },
    {
        name: " Long Mare Lashkara",
        artist: "Abeer Arora",
        img: "c7",
        src: "7",
    },
    {
        name: "We will go",
        artist: "Aarman Malik",
        img: "c8",
        src: "8",
    },
    {
        name: "Feelings - Female Version",
        artist: "Vatsala",
        img: "c3",
        src: "9",
    },
    {
        name: "Satranga",
        artist: "Arjit Singh, siddharth",
        img: "c10",
        src: "10",
    },
    {
        name: "Kudmiya",
        artist: "Film version- Shahid Mallya",
        img: "c11",
        src: "11",
    },
    {
        name: "Heeriya",
        artist: "Arjit Singh, Dulquer Salman",
        img: "c12",
        src: "12",
    },
    {
        name: "Raabta-Title Song",
        artist: "Arjit Singh, Pritam",
        img: "c13",
        src: "13",
    },
    {
        name: "Malang Sajna",
        artist: "Sachet Parampara",
        img: "c14",
        src: "14",
    },
    {
        name: "O Maahi - Dunki",
        artist: "Pritam, Arjit Singh",
        img: "c16",
        src: "16",
    },
    {
        name: "Ve Haniya Ve Dil Janiya",
        artist: "Jubin Nutiyal, Danny",
        img: "c17",
        src: "17",
    },
    {
        name: "Teri Baaton Mein Aise Uljha Jiya",
        artist: "Raghav, Tanishk Ban..",
        img: "c18",
        src: "18",
    },
]

